version: '2'

services:
    ksam-adapter:
        image: ksam-adapter:latest
        ports:
            - "8083:8083"
            - "8088:8080"
        volumes:
        - /home/revere/ezb/ksam_data/:/tmp/weka
        network_mode: host

 # microservice city data monitor
   # cityreporter:
   #     image: cityreporter
   #     network_mode: host
   #     depends_on:
   #     - ksam-adapter
   #     volumes:
   #     - /weka_ksam/:/tmp/weka
